# Generated by Django 6.0.2 on 2026-06-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_department_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
