# Generated by Django 6.0.2 on 2026-07-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_alter_course_course_code'),
        ('students', '0003_alter_student_matric_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='2025/2026', max_length=9)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='students.student')),
            ],
            options={
                'ordering': ['-registered_date'],
                'unique_together': {('student', 'course', 'session')},
            },
        ),
    ]
